// AUTO-GENERATED by scripts/register-games.ts — do not edit manually.
// Re-run `npm run build:games` to regenerate.

import { GameEntry } from "./types";

export const gameRegistry: GameEntry[] = [
  {
    "slug": "example-game",
    "title": "Example Game",
    "description": "A simple example game demonstrating the React game integration.",
    "type": "react",
    "entry": "src/index.tsx",
    "thumbnail": "thumbnail.svg",
    "tags": [
      "example",
      "demo"
    ],
    "minPlayers": 1,
    "maxPlayers": 1,
    "version": "1.0.0"
  },
  {
    "slug": "python-example",
    "title": "Python Bouncing Ball",
    "description": "A simple bouncing ball demo running Python in the browser via Pyodide.",
    "type": "python",
    "entry": "src/main.py",
    "thumbnail": "thumbnail.svg",
    "tags": [
      "python",
      "demo",
      "example"
    ],
    "minPlayers": 1,
    "maxPlayers": 1,
    "version": "1.0.0"
  }
];
