// Reads all games/*/game.config.json files and generates lib/game-registry.ts.
// Run: npx tsx scripts/register-games.ts

import fs from "node:fs";
import path from "node:path";

interface GameConfig {
  slug: string;
  title: string;
  description: string;
  type: "react" | "python" | "python-server" | "static";
  entry: string;
  thumbnail: string;
  tags?: string[];
  minPlayers?: number;
  maxPlayers?: number;
  version?: string;
  buildCommand?: string;
  buildOutput?: string;
  pythonVersion?: string;
  serverPort?: number;
  serverUrl?: string;
}

const GAMES_DIR = path.resolve(__dirname, "../games");
const OUTPUT_FILE = path.resolve(__dirname, "../lib/game-registry.ts");

function main() {
  const entries: GameConfig[] = [];

  if (!fs.existsSync(GAMES_DIR)) {
    console.log("No games/ directory found. Writing empty registry.");
    writeRegistry(entries);
    return;
  }

  const dirs = fs.readdirSync(GAMES_DIR, { withFileTypes: true });

  for (const dir of dirs) {
    if (!dir.isDirectory()) continue;

    const configPath = path.join(GAMES_DIR, dir.name, "game.config.json");
    if (!fs.existsSync(configPath)) {
      console.warn(`  SKIP: ${dir.name}/ — no game.config.json`);
      continue;
    }

    try {
      const raw = fs.readFileSync(configPath, "utf-8");
      const config: GameConfig = JSON.parse(raw);

      // Validate required fields
      const required = ["slug", "title", "description", "type", "entry", "thumbnail"] as const;
      for (const field of required) {
        if (!config[field]) {
          console.error(`  ERROR: ${dir.name}/game.config.json missing required field: ${field}`);
          process.exit(1);
        }
      }

      // Validate slug matches directory name
      if (config.slug !== dir.name) {
        console.error(
          `  ERROR: ${dir.name}/game.config.json slug "${config.slug}" does not match directory name "${dir.name}"`
        );
        process.exit(1);
      }

      // Validate type
      const validTypes = ["react", "python", "python-server", "static"];
      if (!validTypes.includes(config.type)) {
        console.error(
          `  ERROR: ${dir.name}/game.config.json has invalid type "${config.type}"`
        );
        process.exit(1);
      }

      entries.push(config);
      console.log(`  OK: ${config.slug} (${config.type})`);
    } catch (err) {
      console.error(`  ERROR: Failed to parse ${configPath}:`, err);
      process.exit(1);
    }
  }

  writeRegistry(entries);
}

function writeRegistry(entries: GameConfig[]) {
  const entriesJson = entries.map((e) => ({
    slug: e.slug,
    title: e.title,
    description: e.description,
    type: e.type,
    entry: e.entry,
    thumbnail: e.thumbnail,
    tags: e.tags ?? [],
    minPlayers: e.minPlayers ?? 1,
    maxPlayers: e.maxPlayers ?? 1,
    version: e.version ?? "0.0.0",
    ...(e.serverUrl ? { serverUrl: e.serverUrl } : {}),
  }));

  const code = `// AUTO-GENERATED by scripts/register-games.ts — do not edit manually.
// Re-run \`npm run build:games\` to regenerate.

import { GameEntry } from "./types";

export const gameRegistry: GameEntry[] = ${JSON.stringify(entriesJson, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, code, "utf-8");
  console.log(`\nWrote ${entries.length} game(s) to lib/game-registry.ts`);
}

main();
